"""empty message

Revision ID: 820c551032b8
Revises: c4d02a85c034
Create Date: 2024-02-23 10:55:24.454991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820c551032b8'
down_revision = 'c4d02a85c034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_table_patient_id_patients_table'), 'patients_table', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_table_patient_id_patients_table'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    op.drop_table('patients_table')
    # ### end Alembic commands ###
